### ISSUE TITLE
Write readme with motivation / instructions on how to use

### ISSUE THREAD

**Issue by juanpujol** [Beakyn/es-migration-cli#2]
This lib its great @hileomsi ! And the motivation to create it deserves to be shared! Also, for future Beakyn generations (LOL) docs on how to use it would be great!

**Comment by hileomsi** [comment]
I have written a readme file here:
https://github.com/Beakyn/onsmart-ops/blob/main/node-packages/onsmart-elasticsearch-migration-cli/README.md
